import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraUI } from "@/providers/ChakraUI";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Next App",
    description: "Generated by create next@14 app",
};

const RootLayout = ({ 
    children, 
    params: {
        lang
    } 
}: LangProps) => {
    return (
        <html lang={lang}>
            <body className={inter.className}>
                <ChakraUI>
                    {children}
                </ChakraUI>
            </body>
        </html>
    );
}

export default RootLayout;
