import type { Metadata } from "next";
/* import { Inter } from "next/font/google"; */
import { ChakraUI } from "@/providers/ChakraUI";

/* const inter = Inter({ subsets: ["latin"] }); */

export const metadata: Metadata = {
    title: "Next App",
    description: "Generated by create next@14 app",
};

const RootLayout = ({ 
    children
}: ReactChildren) => {
    return (
        <html >
            <body>
                <ChakraUI>
                    {children}
                </ChakraUI>
            </body>
        </html>
    );
}

export default RootLayout;
